openapi: 3.1.0
info:
  title: Ducto Feature Flags API
  version: 1.0.0
  description: |
    A lightweight feature flag API served via the `ducto-flags serve` CLI.
    Supports environment-aware flag evaluation, secure access, and conditional responses via `304 Not Modified`.

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /api/flags:
    get:
      summary: Get all feature flags or evaluate a single flag
      description: >
        Returns either all available flags (definition form), or evaluates a single flag for a given context.
        Supports optional `If-Modified-Since` for caching, and bearer token authentication if enabled.
      parameters:
        - name: key
          in: query
          required: false
          description: The specific flag key to evaluate
          schema:
            type: string
        - name: Authorization
          in: header
          required: false
          description: Bearer token for access control (if configured)
          schema:
            type: string
        - name: If-Modified-Since
          in: header
          required: false
          description: Timestamp of last known state; returns 304 if unchanged
          schema:
            type: string
            format: date-time
        - name: env
          in: query
          required: false
          description: Optional context key (used if evaluating)
          schema:
            type: string
        - name: user_id
          in: query
          required: false
          description: Optional context key (used if evaluating)
          schema:
            type: string
      responses:
        "200":
          description: Successful response with flag(s)
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      enabled:
                        type: boolean
                  - type: object
                    additionalProperties:
                      $ref: '#/components/schemas/Flag'
        "304":
          description: No changes since last check (based on `If-Modified-Since`)
        "401":
          description: Unauthorized (missing or invalid token)

components:
  schemas:
    Flag:
      type: object
      properties:
        enabled:
          type: boolean
        rules:
          type: array
          items:
            type: object
        description:
          type: string
